ruby_version_path = File.expand_path('../.ruby-version', __FILE__)
ruby_version = IO.binread(ruby_version_path).strip

ruby(ruby_version)

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'sinatra'
gem 'puma'
