#! /usr/bin/env ruby
#
  require_relative '../../lib/senv'
  require_relative '../../lib/util'

#
  script = __FILE__
  script_dir = File.expand_path(File.dirname(script))
  root = File.dirname(script_dir)

#
  Senv.load

#
  proxy_port = ENV.fetch('PROXY_PORT')
  frontend_port = ENV.fetch('FRONTEND_PORT'){ ENV.fetch('PORT') }
  backend_port = ENV.fetch('BACKEND_PORT')

#
  cmd = "PORT=#{ frontend_port } npm start"

#
  Util.serve!(cmd, :root => root, :port => frontend_port)

#
  sleep
