#! /usr/bin/env ruby
#
  require_relative '../../lib/util'

#
  script = __FILE__
  script_dir = File.expand_path(File.dirname(script))

#
  root = File.dirname(script_dir)
  port = ENV['BACKEND_PORT'] || ENV['PORT'] || '4000'

  cmd = "bundle exec ruby app.rb -p #{ port }"

  env = {
    'PORT' => port
  }

  Util.serve!(cmd, :root => root, :env => env)

  sleep
