#! /usr/bin/env ruby
#
  script = __FILE__
  script_dir = File.expand_path(File.dirname(script))
  root = File.dirname(script_dir)

#
  name = root.dup
  port = ENV['BACKEND_PORT'] || ENV['PORT'] || '4000'
  senv = ENV['SENV'] || 'development'

#
  #Bundler.with_unbundled_env do
    Dir.chdir(root)
    #Bundler.require

    command = %W[
      bundle exec ruby app.rb -p #{ port }
    ]
    cmd = command.join(' ').strip

    ENV['PORT'] = port
    ENV['SENV'] = senv

    env = "PORT=#{ port } SENV=#{ senv }"

    loop do
      puts "### #{ name }: #{ env } #{ cmd }"
      system(cmd)
      sleep 4.20
    end
  #end

BEGIN {
  STDOUT.sync = true
  STDERR.sync = true

  #require 'bundler'
}
