#! /usr/bin/env ruby
#
  script = __FILE__
  script_dir = File.expand_path(File.dirname(script))
  root = File.dirname(script_dir)

#
  name = root.dup
  port = ENV['PORT'] || '8080'
  mode = ENV['MODE'] || 'development'

#
  Bundler.with_unbundled_env do
  #system 'env|grep -i BUNDLE'
  #system 'env|grep -i PORT'
    #system 'echo PATH=$PATH'
    #system 'which http-proxy'
    #system 'curl http://localhost:3000'
    #system 'curl http://localhost:4000'

  #
    Dir.chdir(root)

  #
    command = %W[
      http-proxy --port #{ port } 3000 /a=localhost:4000
    ]

    cmd = command.join(' ').strip

    ENV['PORT'] = port
    ENV['MODE'] = port

    env = "PORT=#{ port } MODE=#{ mode }"

    loop do
      puts "### #{ name }: #{ env } #{ cmd }"
      system(cmd)
      sleep 4.20
    end
  end

BEGIN {
  STDOUT.sync = true
  STDERR.sync = true

  require 'bundler'
}
