#! /usr/bin/env ruby
#
  require_relative '../../lib/util'

#
  script = __FILE__
  script_dir = File.expand_path(File.dirname(script))

#
  root = File.dirname(script_dir)
  port = ENV['PORT'] || '8080'
  frontend_port = ENV['FRONTEND_PORT'] || '3000'
  backend_port = ENV['BACKEND_PORT'] || '4000'

  cmd = "http-proxy --verbose --port #{ port } #{ frontend_port } /a=localhost:#{ backend_port }"

  env = {
    'PORT' => port
  }

  Util.serve!(cmd, :root => root, :env => env)

  sleep
